// Auto-generated from src/utils/selectionDefinitions.js
// Maps pathway/career world title → first-paragraph professional description
// Used by buildMeta() to inject item.description for LLM grounding.

"use strict";

const PATHWAY_DESCRIPTIONS = {
  "Data, Analytics & Quantitative Insight": `Data, Analytics & Quantitative Insight is a career world focused on using evidence, numbers, modelling, and structured thinking to understand problems and support better decisions. People in this world help organisations uncover patterns, predict outcomes, measure performance, reduce risk, and make sense of increasingly complex information.`,

  "Software, AI & Digital Systems": `Software, AI & Digital Systems is a career world centred around building the digital technologies that power modern life. People in this area create software, intelligent systems, digital platforms, and technical infrastructure that help individuals and organisations communicate, solve problems, automate processes, and interact with technology more effectively.`,

  "Engineering, Manufacturing & Infrastructure": `Engineering, Manufacturing & Infrastructure is a career world focused on designing, building, improving, and maintaining the physical systems and technologies that support modern society. People in this world help create everything from machines, transport systems, and energy networks to manufacturing processes, robotics, and large-scale infrastructure.`,

  "Architecture, Built Environment & Spatial Design": `Architecture, Built Environment & Spatial Design is a career world focused on shaping the places and spaces where people live, work, learn, travel, and connect. People in this world combine design imagination with practical planning, technical understanding, and awareness of how physical environments affect human behaviour and wellbeing.`,

  "Science, Research & Laboratory Innovation": `Science, Research & Laboratory Innovation is a career world focused on discovery, experimentation, and advancing human understanding through scientific investigation. People in this area help develop new knowledge, technologies, medicines, materials, and solutions that improve the way we understand and interact with the world.`,

  "Health Care & Clinical Practice": `Health Care & Clinical Practice is a career world centred around improving health, wellbeing, and quality of life through compassionate, evidence-informed care. People in this area work directly with individuals and communities to diagnose, treat, support, rehabilitate, and care for others across a wide range of clinical and healthcare settings.`,

  "Psychology, Behaviour & Human Insight": `Psychology, Behaviour & Human Insight is a career world focused on understanding how people think, feel, behave, learn, and develop. People in this area help improve wellbeing, relationships, decision-making, communication, and human performance across individuals, organisations, and society.`,

  "Education, Coaching & People Development": `Education, Coaching & People Development is a career world focused on helping people learn, grow, build confidence, and reach their potential. People in this area design, deliver, and support learning experiences across schools, early years settings, universities, workplaces, community organisations, and digital learning environments.`,

  "Law, Governance & Public Impact": `Law, Governance & Public Impact is a career world focused on rules, rights, accountability, public decision-making, and the systems that help societies function fairly. People in this world support legal processes, improve governance, analyse policy, manage risk, investigate wrongdoing, and help organisations act responsibly.`,

  "Business Strategy, Commercial & Leadership": `Business Strategy, Commercial & Leadership is a career world focused on helping organisations make better decisions, operate effectively, grow sustainably, and respond to change. People in this area connect ideas, people, processes, customers, partners, and resources so that organisations can deliver value and achieve their goals.`,

  "Finance, Economics & Investment": `Finance, Economics & Investment is a career world focused on understanding money, markets, value, risk, and how financial decisions shape organisations and economies. People in this area help individuals, businesses, investors, and institutions allocate resources, manage uncertainty, evaluate performance, and make informed financial choices.`,

  "Entrepreneurship, Innovation & Venture Building": `Entrepreneurship, Innovation & Venture Building is a career world focused on creating new ideas, building ventures, solving problems, and turning opportunities into real products, services, or organisations. People in this area often work in uncertain, fast-moving environments where they test ideas, attract support, build partnerships, and find practical ways to bring something new into the world.`,

  "Marketing, Media & Communication": `Marketing, Media & Communication is a career world focused on understanding audiences, shaping messages, building brands, and helping people connect with ideas, products, organisations, and causes. People in this area combine creativity, insight, storytelling, and strategy to influence how information is shared and how audiences respond.`,

  "Creative Arts, Design & Experience": `Creative Arts, Design & Experience is a career world centred around shaping how people experience products, brands, spaces, media, and digital environments. People in this world help turn ideas into experiences that are engaging, useful, visually compelling, and emotionally memorable. Their work influences how people interact with technology, communicate messages, connect with brands, and navigate both physical and digital spaces.`,

  "Environment, Sustainability & Planetary Futures": `Environment, Sustainability & Planetary Futures is a career world focused on protecting natural systems, reducing environmental harm, and helping organisations and societies transition towards more sustainable ways of living and working. People in this area use science, policy, strategy, data, and systems thinking to understand environmental challenges and design practical responses.`,

  "Society, Culture, Languages & Global Affairs": `Society, Culture, Languages & Global Affairs is a career world focused on understanding people, places, cultures, societies, and international relationships. People in this area help organisations and communities interpret social change, communicate across cultures, analyse global issues, and work with diverse groups and perspectives.`,

  "Core Data Analysis & Business Insight": `Core Data Analysis & Business Insight involves turning raw data into clear evidence that helps organisations understand performance, solve problems, and make better decisions. People in this pathway clean and analyse datasets, build reports, identify trends, and translate findings into practical recommendations for teams and leaders. The work combines structured thinking with problem-solving and often involves working with dashboards, spreadsheets, databases, reporting tools, statistical methods, or analytical models.`,

  "Business Intelligence & Reporting": `Business Intelligence & Reporting focuses on creating dashboards, reports, and performance measures that help organisations monitor what is happening across their operations. People in this pathway connect data sources, track key indicators, visualise trends, and make information easier for managers and teams to use. The work combines structured thinking with problem-solving and often involves working with dashboards, spreadsheets, databases, reporting tools, statistical methods, or analytical models.`,

  "Customer & Market Insight": `Customer & Market Insight focuses on understanding customers, audiences, competitors, and market behaviour through research and data analysis. People in this pathway combine survey results, behavioural data, interviews, market reports, and commercial evidence to explain what people need, value, and respond to. The work combines structured thinking with problem-solving and often involves working with dashboards, spreadsheets, databases, reporting tools, statistical methods, or analytical models.`,

  "Risk & Quantitative Analysis": `Risk & Quantitative Analysis involves using statistical, financial, and mathematical techniques to estimate uncertainty, model risk, and support decisions where accuracy matters. People in this pathway assess probability, pricing, exposure, loss scenarios, and future outcomes in areas such as insurance, banking, investment, and operations. The work combines structured thinking with problem-solving and often involves working with dashboards, spreadsheets, databases, reporting tools, statistical methods, or analytical models.`,

  "Data Science & Advanced Modelling": `Data Science & Advanced Modelling involves using statistics, programming, experimentation, and modelling to explain complex patterns and predict future outcomes. People in this pathway build models, test assumptions, analyse large datasets, and turn advanced analysis into tools or recommendations that support decision-making. The work combines structured thinking with problem-solving and often involves working with dashboards, spreadsheets, databases, reporting tools, statistical methods, or analytical models.`,

  "Machine Learning & Applied AI": `Machine Learning & Applied AI focuses on applying data, models, and algorithms to create systems that can predict, classify, recommend, or automate decisions. People in this pathway prepare training data, evaluate model performance, test AI outputs, and help organisations use intelligent systems responsibly in real settings. The work combines structured thinking with problem-solving and often involves working with dashboards, spreadsheets, databases, reporting tools, statistical methods, or analytical models.`,

  "Product, Growth & Experimentation Analytics": `Product, Growth & Experimentation Analytics focuses on using data to improve digital products, user journeys, customer acquisition, and growth decisions. People in this pathway analyse product behaviour, run experiments, interpret conversion funnels, and help teams decide what to build, test, or improve next. The work combines structured thinking with problem-solving and often involves working with dashboards, spreadsheets, databases, reporting tools, statistical methods, or analytical models.`,

  "Software Engineering": `Software Engineering involves designing, coding, testing, and maintaining software applications and systems. People in this pathway build features, solve technical problems, review code, improve performance, and work with product or design teams to turn user needs into reliable digital products. The work combines logical problem-solving with technical creativity and often involves programming, testing, debugging, system design, documentation, security awareness, or collaboration across digital product teams.`,

  "Backend & Platform Engineering": `Backend & Platform Engineering focuses on the server-side systems, APIs, databases, infrastructure, and platforms that allow digital products to run reliably at scale. People in this pathway design system architecture, manage data flows, improve performance, and build the technical foundations that users do not see but depend on. The work combines logical problem-solving with technical creativity and often involves programming, testing, debugging, system design, documentation, security awareness, or collaboration across digital product teams.`,

  "Frontend & Web Development": `Frontend & Web Development focuses on building the parts of websites, apps, and digital products that users see and interact with directly. People in this pathway turn designs into responsive interfaces, improve usability and accessibility, and use code to create polished digital experiences. The work combines logical problem-solving with technical creativity and often involves programming, testing, debugging, system design, documentation, security awareness, or collaboration across digital product teams.`,

  "Data Engineering": `Data Engineering involves building the pipelines, databases, and data platforms that allow organisations to collect, store, process, and use data reliably. People in this pathway design data flows, manage infrastructure, improve data quality, and make sure analysts, products, and AI systems have dependable information to work with. The work combines logical problem-solving with technical creativity and often involves programming, testing, debugging, system design, documentation, security awareness, or collaboration across digital product teams.`,

  "Quality Assurance & Test Engineering": `Quality Assurance & Test Engineering focuses on making sure software works correctly, safely, and consistently before and after it reaches users. People in this pathway design test plans, automate checks, identify bugs, verify releases, and help development teams improve product quality. The work combines logical problem-solving with technical creativity and often involves programming, testing, debugging, system design, documentation, security awareness, or collaboration across digital product teams.`,

  "Cyber Security": `Cyber Security involves protecting digital systems, networks, data, and users from threats, misuse, and unauthorised access. People in this pathway monitor risks, investigate incidents, test vulnerabilities, strengthen controls, and help organisations respond to an increasingly complex threat landscape. The work combines logical problem-solving with technical creativity and often involves programming, testing, debugging, system design, documentation, security awareness, or collaboration across digital product teams.`,

  "AI & Machine Learning Engineering": `AI & Machine Learning Engineering focuses on turning AI models into working systems, products, and services. People in this pathway build model pipelines, deploy machine learning solutions, monitor performance, integrate AI into software products, and work on the technical infrastructure that makes intelligent systems usable at scale. The work combines logical problem-solving with technical creativity and often involves programming, testing, debugging, system design, documentation, security awareness, or collaboration across digital product teams.`,

  "Mechanical Design & Development Engineering": `Mechanical Design & Development Engineering involves designing, testing, and improving mechanical products, components, and systems. People in this pathway use engineering principles, CAD tools, prototyping, simulation, and testing to develop physical solutions for industries such as manufacturing, transport, energy, aerospace, and consumer products. The work combines technical knowledge with practical judgement and often involves design, modelling, testing, production, maintenance, safety, quality, cost, and real-world constraints.`,

  "Electrical & Electronic Engineering": `Electrical & Electronic Engineering focuses on electrical systems, circuits, electronics, control systems, sensors, power, and connected technologies. People in this pathway design, test, troubleshoot, and improve the hardware and electrical systems that support products, infrastructure, automation, communications, and energy networks. The work combines technical knowledge with practical judgement and often involves design, modelling, testing, production, maintenance, safety, quality, cost, and real-world constraints.`,

  "Manufacturing & Production Engineering": `Manufacturing & Production Engineering focuses on how products are made efficiently, safely, consistently, and at scale. People in this pathway improve production methods, quality control, equipment use, workflow, and process reliability across factories, engineering firms, and advanced manufacturing environments. The work combines technical knowledge with practical judgement and often involves design, modelling, testing, production, maintenance, safety, quality, cost, and real-world constraints.`,

  "Process & Industrial Engineering": `Process & Industrial Engineering involves improving systems, workflows, processes, and operations so that organisations can deliver better results with less waste. People in this pathway analyse bottlenecks, redesign processes, optimise resources, and use data to improve productivity, quality, and efficiency. The work combines technical knowledge with practical judgement and often involves design, modelling, testing, production, maintenance, safety, quality, cost, and real-world constraints.`,

  "Systems Engineering": `Systems Engineering focuses on designing and integrating complex systems where many technical parts need to work together reliably. People in this pathway define requirements, coordinate components, manage interfaces, test performance, and ensure that complex engineering solutions function as a whole. The work combines technical knowledge with practical judgement and often involves design, modelling, testing, production, maintenance, safety, quality, cost, and real-world constraints.`,

  "Robotics & Automation Engineering": `Robotics & Automation Engineering involves designing, programming, testing, and improving robotic and automated systems. People in this pathway work with sensors, control systems, mechanical design, software, and production processes to automate tasks, improve precision, and support safer or more efficient operations. The work combines technical knowledge with practical judgement and often involves design, modelling, testing, production, maintenance, safety, quality, cost, and real-world constraints.`,

  "Civil & Structural Engineering": `Civil & Structural Engineering focuses on designing, analysing, and delivering infrastructure such as buildings, bridges, roads, foundations, drainage systems, and structural frameworks. People in this pathway assess safety, materials, loads, site conditions, and construction methods to create reliable built assets. The work combines technical knowledge with practical judgement and often involves design, modelling, testing, production, maintenance, safety, quality, cost, and real-world constraints.`,

  "Infrastructure, Maintenance & Asset Engineering": `Infrastructure, Maintenance & Asset Engineering focuses on keeping engineering assets, infrastructure, equipment, and systems safe, reliable, and cost-effective over time. People in this pathway plan maintenance, monitor performance, manage asset lifecycles, reduce downtime, and improve the long-term dependability of critical systems. The work combines technical knowledge with practical judgement and often involves design, modelling, testing, production, maintenance, safety, quality, cost, and real-world constraints.`,

  "Architecture": `Architecture involves designing buildings and spaces that balance creativity, function, technical requirements, regulation, sustainability, and human experience. People in this pathway develop concepts, produce drawings, coordinate with engineers and clients, and help turn design ideas into buildable environments. The work combines creativity with technical, spatial, environmental, and commercial awareness, often requiring people to balance design quality with regulation, cost, sustainability, usability, and delivery.`,

  "Town Planning & Urban Development": `Town Planning & Urban Development focuses on how towns, cities, neighbourhoods, and regions should grow and change over time. People in this pathway assess development proposals, housing needs, transport, land use, community impact, and policy requirements to shape better places. The work combines creativity with technical, spatial, environmental, and commercial awareness, often requiring people to balance design quality with regulation, cost, sustainability, usability, and delivery.`,

  "Architectural Technology & BIM": `Architectural Technology & BIM focuses on the technical design, digital modelling, and detailed coordination needed to turn architectural ideas into buildable projects. People in this pathway use BIM software, technical drawings, building standards, materials knowledge, and digital workflows to support accurate design delivery. The work combines creativity with technical, spatial, environmental, and commercial awareness, often requiring people to balance design quality with regulation, cost, sustainability, usability, and delivery.`,

  "Construction Project Delivery": `Construction Project Delivery involves coordinating construction projects so that buildings and infrastructure are delivered safely, on time, within budget, and to the required quality. People in this pathway manage site activity, contractors, schedules, documentation, risks, and stakeholder communication. The work combines creativity with technical, spatial, environmental, and commercial awareness, often requiring people to balance design quality with regulation, cost, sustainability, usability, and delivery.`,

  "Surveying & Cost Consultancy": `Surveying & Cost Consultancy focuses on the measurement, cost, condition, value, and commercial management of buildings and construction projects. People in this pathway estimate costs, manage budgets, assess buildings, advise on contracts, and help clients make informed property and construction decisions. The work combines creativity with technical, spatial, environmental, and commercial awareness, often requiring people to balance design quality with regulation, cost, sustainability, usability, and delivery.`,

  "Sustainability & Building Performance": `Sustainability & Building Performance focuses on improving how buildings use energy, materials, space, and resources across their lifecycle. People in this pathway assess environmental performance, advise on low-carbon design, analyse building data, and help projects meet sustainability and wellbeing goals. The work combines creativity with technical, spatial, environmental, and commercial awareness, often requiring people to balance design quality with regulation, cost, sustainability, usability, and delivery.`,

  "Laboratory Science": `Laboratory Science involves carrying out controlled tests, experiments, and analyses in laboratory settings. People in this pathway prepare samples, follow protocols, operate scientific equipment, record results accurately, and support research, diagnostics, quality control, or product development. The work combines curiosity with rigour and often involves experiments, testing, observation, literature, data, protocols, quality standards, and careful interpretation of evidence.`,

  "R&D Science": `R&D Science focuses on developing new knowledge, products, materials, processes, or technologies through research and experimentation. People in this pathway design studies, test hypotheses, analyse results, refine prototypes, and contribute to innovation in scientific or industrial settings. The work combines curiosity with rigour and often involves experiments, testing, observation, literature, data, protocols, quality standards, and careful interpretation of evidence.`,

  "Materials & Chemical Analysis": `Materials & Chemical Analysis involves testing, characterising, and improving chemicals, materials, compounds, and substances. People in this pathway use analytical techniques, laboratory equipment, quality standards, and scientific judgement to understand composition, performance, safety, and potential applications. The work combines curiosity with rigour and often involves experiments, testing, observation, literature, data, protocols, quality standards, and careful interpretation of evidence.`,

  "Biomedical & Clinical Research": `Biomedical & Clinical Research focuses on understanding disease, treatment, human biology, and clinical evidence. People in this pathway support studies, analyse biological or patient-related data, help run clinical research, and contribute to the development or evaluation of healthcare interventions. The work combines curiosity with rigour and often involves experiments, testing, observation, literature, data, protocols, quality standards, and careful interpretation of evidence.`,

  "Scientific Data & Bioinformatics": `Scientific Data & Bioinformatics involves using computational tools, statistics, and biological or scientific datasets to answer research questions. People in this pathway analyse genomic, biomedical, environmental, or experimental data and help scientists interpret complex patterns at scale. The work combines curiosity with rigour and often involves experiments, testing, observation, literature, data, protocols, quality standards, and careful interpretation of evidence.`,

  "Clinical Trials & Translational Research": `Clinical Trials & Translational Research focuses on moving scientific discoveries towards practical healthcare use through trials, evidence generation, and applied research. People in this pathway coordinate studies, manage trial data, support governance, and help test whether new treatments or interventions are safe and effective. The work combines curiosity with rigour and often involves experiments, testing, observation, literature, data, protocols, quality standards, and careful interpretation of evidence.`,

  "Clinical Medicine / Doctor": `Clinical Medicine involves diagnosing illness, treating patients, managing care, and making evidence-based decisions in hospitals, GP practices, and specialist services. People in this pathway combine medical knowledge, communication, investigation, clinical judgement, and teamwork to support patients through prevention, treatment, recovery, and long-term care. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Surgery & Procedural Medicine": `Surgery & Procedural Medicine focuses on treating disease, injury, and physical conditions through operations, procedures, and highly technical clinical interventions. People in this pathway assess patients, plan procedures, operate with precision, manage risk, and support recovery alongside multidisciplinary teams. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Acute, Emergency & Critical Care": `Acute, Emergency & Critical Care involves responding to urgent, complex, and high-risk health situations where rapid assessment and decision-making are essential. People in this pathway stabilise patients, manage emergencies, interpret clinical information quickly, and work closely with teams under pressure. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Mental Health & Behavioural Medicine": `Mental Health & Behavioural Medicine focuses on diagnosing, treating, and supporting people experiencing mental health, behavioural, emotional, or psychiatric difficulties. People in this pathway combine medical knowledge, psychological understanding, risk assessment, communication, and long-term care planning. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Diagnostic & Investigative Medicine": `Diagnostic & Investigative Medicine focuses on identifying disease and guiding treatment through imaging, pathology, genetics, microbiology, and other specialist investigations. People in this pathway interpret evidence, run or review tests, and provide critical information that supports accurate clinical decisions. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Public Health Medicine, Epidemiology & Health Policy": `Public Health Medicine, Epidemiology & Health Policy focuses on improving health at population level rather than treating one patient at a time. People in this pathway analyse disease patterns, design prevention strategies, advise on policy, monitor health risks, and support system-wide decisions. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Academic Medicine & Clinical Research": `Academic Medicine & Clinical Research combines clinical knowledge with research, teaching, evidence generation, and innovation. People in this pathway investigate medical questions, contribute to trials or studies, teach future professionals, and help translate evidence into better healthcare practice. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Healthcare Leadership & Service Improvement": `Healthcare Leadership & Service Improvement focuses on improving how healthcare services are organised, delivered, measured, and experienced. People in this pathway work on quality improvement, patient safety, service redesign, operations, strategy, and leadership across healthcare systems. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Digital Health, Healthtech & Medical Innovation": `Digital Health, Healthtech & Medical Innovation focuses on using technology, data, AI, and product innovation to improve healthcare delivery and patient outcomes. People in this pathway help design, evaluate, implement, or advise on digital tools, health platforms, and technology-enabled care models. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Nursing": `Nursing focuses on delivering safe, compassionate, and evidence-informed care across hospitals, communities, mental health services, children’s services, and specialist settings. People in this pathway assess needs, monitor patients, provide treatment, coordinate care, and support people through illness, recovery, and long-term conditions. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Public Health Nursing & Health Visiting": `Public Health Nursing & Health Visiting focuses on prevention, family health, child development, community wellbeing, and early support. People in this pathway work with families, children, communities, and services to identify needs, reduce health risks, and promote healthier lives. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Clinical Research Nursing": `Clinical Research Nursing combines patient care with the delivery of clinical studies and trials. People in this pathway support participants, collect accurate data, follow research protocols, coordinate appointments, and help generate evidence for new treatments and healthcare practices. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Nurse Education & Leadership": `Nurse Education & Leadership focuses on developing nursing practice, supporting teams, improving care quality, and helping other professionals learn. People in this pathway may supervise staff, design training, lead services, support clinical governance, and drive improvements in patient care. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Midwifery": `Midwifery focuses on supporting women, babies, and families through pregnancy, birth, and the early postnatal period. People in this pathway provide clinical care, emotional support, health education, risk monitoring, and safe decision-making during one of the most important stages of family life. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Rehabilitation & Functional Independence": `Rehabilitation & Functional Independence focuses on helping people recover movement, function, confidence, and independence after illness, injury, disability, or long-term health challenges. People in this pathway assess abilities, design therapy plans, adapt environments, and support practical progress in daily life. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Clinical Science & Laboratory Diagnostics": `Clinical Science & Laboratory Diagnostics focuses on using scientific testing and interpretation to support diagnosis, treatment, and disease monitoring. People in this pathway analyse samples, operate specialist equipment, validate results, and provide evidence that clinicians rely on for patient care. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Diagnostics, Imaging & Clinical Support (Legacy Unrouted)": `Diagnostics, Imaging & Clinical Support focuses on producing and interpreting clinical images or technical evidence that helps diagnose and monitor health conditions. People in this pathway use regulated equipment, patient-facing skills, and technical judgement to support accurate care decisions. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Pharmacy (Legacy Broad Route)": `Pharmacy focuses on medicines, therapeutics, safety, and patient advice. People in this pathway understand how medicines work, support safe prescribing and dispensing, advise patients and clinicians, and help make sure treatments are effective, appropriate, and used responsibly. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Paramedic Practice & Emergency Care": `Paramedic Practice & Emergency Care involves responding to urgent health situations outside hospital and making rapid decisions in unpredictable environments. People in this pathway assess patients, provide emergency treatment, manage risk, communicate under pressure, and coordinate safe handover into wider care systems. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Emergency Planning & Ambulance Service Leadership": `Emergency Planning & Ambulance Service Leadership focuses on organising urgent-care systems, emergency response capacity, resilience planning, and operational improvement. People in this pathway coordinate services, plan for incidents, manage resources, and improve how emergency care is delivered. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Public Health & Health Improvement": `Public Health & Health Improvement focuses on preventing illness, reducing inequalities, and improving health across communities. People in this pathway design campaigns, analyse population needs, support local services, and work on practical interventions that help people live healthier lives. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Healthcare Operations & Service Improvement": `Healthcare Operations & Service Improvement focuses on making healthcare services safer, smoother, more efficient, and more responsive to patient needs. People in this pathway analyse service data, redesign processes, coordinate projects, and support improvements in quality, access, and delivery. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Social Work & Safeguarding": `Social Work & Safeguarding focuses on protecting vulnerable people, assessing needs and risks, and helping individuals and families access the right support. People in this pathway work across care, health, education, justice, and community systems to promote safety, dignity, and wellbeing. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Dentistry / Dentist": `Dentistry focuses on oral health, diagnosis, prevention, treatment planning, and clinical procedures for teeth, gums, and the wider mouth. People in this pathway combine precision, patient care, technical skill, and health education to prevent and treat dental disease. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Specialist Dentistry": `Specialist Dentistry involves advanced dental practice in areas such as orthodontics, oral surgery, restorative dentistry, or paediatric dentistry. People in this pathway handle more complex cases, use specialist techniques, and provide advanced treatment planning for specific oral health needs. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Dental Research & Academic Dentistry": `Dental Research & Academic Dentistry combines dental knowledge with scientific research, teaching, innovation, and evidence generation. People in this pathway investigate oral health questions, evaluate treatments, teach future dental professionals, and contribute to better practice and policy. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Oral Health Policy & Dental Public Health": `Oral Health Policy & Dental Public Health focuses on improving oral health at population level through prevention, service planning, access, education, and policy. People in this pathway analyse needs, design interventions, and support decisions that reduce inequalities in dental health. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Clinical Pharmacy": `Clinical Pharmacy focuses on optimising medicines for individual patients in hospitals, clinics, GP practices, and specialist services. People in this pathway review prescriptions, advise clinical teams, monitor safety, support treatment decisions, and help patients use medicines effectively. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Community Pharmacy": `Community Pharmacy focuses on accessible medicines advice, dispensing, public health support, and patient-facing services in local communities. People in this pathway advise patients, manage prescriptions, provide services such as vaccinations or checks, and support safe everyday medicine use. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Pharmaceutical Industry & Drug Development": `Pharmaceutical Industry & Drug Development focuses on creating, testing, regulating, and bringing medicines or therapies to market. People in this pathway may work in research, clinical trials, medical affairs, product development, safety, or scientific communication. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Regulatory Affairs & Medicines Safety": `Regulatory Affairs & Medicines Safety focuses on making sure medicines, devices, and health products meet safety, quality, legal, and evidence requirements. People in this pathway prepare submissions, monitor adverse events, manage compliance, and reduce risks to patients. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Medicines Policy & Public Health Pharmacy": `Medicines Policy & Public Health Pharmacy focuses on how medicines are used safely, fairly, and effectively across populations and health systems. People in this pathway work on formularies, access, prescribing policy, public health programmes, and system-wide medicines optimisation. The work combines scientific knowledge with human judgement and often involves assessment, communication, treatment planning, documentation, safety, teamwork, and responsibility for people’s wellbeing.`,

  "Clinical Psychology & Mental Health Support": `Clinical Psychology & Mental Health Support focuses on understanding psychological distress, behaviour, emotional wellbeing, and mental health needs. People in this pathway support assessment, formulation, intervention planning, research, and therapeutic services for individuals and groups. The work combines curiosity about people with ethical judgement and often involves observation, interviews, assessment, research, behaviour analysis, support planning, or translating human insight into practical recommendations.`,

  "Counselling, Psychotherapy & Therapeutic Practice": `Counselling & Psychotherapy focuses on providing structured therapeutic support for people experiencing emotional, relational, or psychological difficulties. People in this pathway build safe helping relationships, explore patterns, support change, and work ethically with clients over time. The work combines curiosity about people with ethical judgement and often involves observation, interviews, assessment, research, behaviour analysis, support planning, or translating human insight into practical recommendations.`,

  "Learning, Development & Behaviour Support": `Learning, Development & Behaviour Support focuses on helping children, young people, or learners overcome barriers to learning, behaviour, confidence, and development. People in this pathway support assessment, intervention, mentoring, inclusion, and collaboration with families or schools. The work combines curiosity about people with ethical judgement and often involves observation, interviews, assessment, research, behaviour analysis, support planning, or translating human insight into practical recommendations.`,

  "People Analytics & Workplace Behaviour": `People Analytics & Workplace Behaviour focuses on understanding employee behaviour, performance, engagement, wellbeing, and organisational culture through data and behavioural insight. People in this pathway analyse workforce patterns and help organisations make better people decisions. The work combines curiosity about people with ethical judgement and often involves observation, interviews, assessment, research, behaviour analysis, support planning, or translating human insight into practical recommendations.`,

  "UX Research & Behavioural Insight": `UX Research & Behavioural Insight focuses on understanding how people think, decide, feel, and interact with products, services, or systems. People in this pathway run research, analyse behaviour, test designs, and translate human insight into better user experiences. The work combines curiosity about people with ethical judgement and often involves observation, interviews, assessment, research, behaviour analysis, support planning, or translating human insight into practical recommendations.`,

  "Justice, Rehabilitation & Behaviour Change": `Justice, Rehabilitation & Behaviour Change focuses on understanding risk, behaviour, rehabilitation, and support within justice or safeguarding contexts. People in this pathway assess needs, support behaviour change, manage risk, and work with individuals, families, or services. The work combines curiosity about people with ethical judgement and often involves observation, interviews, assessment, research, behaviour analysis, support planning, or translating human insight into practical recommendations.`,

  "Primary Teaching & Classroom Practice": `Primary Teaching & Classroom Practice focuses on planning, teaching, and supporting learning for children across the primary curriculum. People in this pathway create lessons, manage classrooms, assess progress, build relationships, and help pupils develop academically, socially, and emotionally. The work combines subject understanding with communication and often involves planning, teaching, coaching, feedback, resource design, learner support, assessment, and adapting to different needs.`,

  "Early Years & Family Support": `Early Years & Family Support focuses on children’s early development, learning, wellbeing, and family support. People in this pathway create safe learning environments, support communication and social development, identify needs early, and work with families or services. The work combines subject understanding with communication and often involves planning, teaching, coaching, feedback, resource design, learner support, assessment, and adapting to different needs.`,

  "SEND & Inclusion Support": `SEND & Inclusion Support focuses on helping learners with special educational needs, disabilities, or additional barriers access education and thrive. People in this pathway adapt learning, provide targeted support, coordinate with professionals, and promote inclusion and confidence. The work combines subject understanding with communication and often involves planning, teaching, coaching, feedback, resource design, learner support, assessment, and adapting to different needs.`,

  "Learning Design & Educational Technology": `Learning Design & Educational Technology focuses on designing learning experiences, resources, courses, and digital tools that help people learn effectively. People in this pathway combine pedagogy, content design, technology, creativity, and evaluation. The work combines subject understanding with communication and often involves planning, teaching, coaching, feedback, resource design, learner support, assessment, and adapting to different needs.`,

  "Training, Learning & Development": `Training, Learning & Development focuses on building skills and capability in workplaces or organisations. People in this pathway design workshops, learning programmes, onboarding, coaching, and development activities that help employees perform and grow. The work combines subject understanding with communication and often involves planning, teaching, coaching, feedback, resource design, learner support, assessment, and adapting to different needs.`,

  "Education Support, Outreach & Student Services": `Education Support, Outreach & Student Services focuses on helping learners access opportunities, navigate education, and receive the right practical or pastoral support. People in this pathway coordinate services, advise students, run outreach, and support progression. The work combines subject understanding with communication and often involves planning, teaching, coaching, feedback, resource design, learner support, assessment, and adapting to different needs.`,

  "Legal Support & Casework": `Legal Support & Casework focuses on supporting legal processes, preparing documents, researching cases, managing evidence, and helping clients or organisations navigate legal issues. People in this pathway work with solicitors, legal teams, courts, or advice services. The work combines analytical thinking with responsibility and often involves reading carefully, interpreting evidence, preparing documents, applying rules, managing risk, and communicating clearly with stakeholders.`,

  "Governance, Risk & Compliance": `Governance, Risk & Compliance focuses on helping organisations follow rules, manage risks, maintain controls, and act responsibly. People in this pathway monitor regulation, review policies, assess compliance, document decisions, and support ethical organisational behaviour. The work combines analytical thinking with responsibility and often involves reading carefully, interpreting evidence, preparing documents, applying rules, managing risk, and communicating clearly with stakeholders.`,

  "Public Affairs & Advocacy": `Public Affairs & Advocacy focuses on influencing decisions, representing interests, and communicating with policymakers, stakeholders, communities, or the public. People in this pathway monitor policy, build relationships, prepare briefings, and support campaigns or advocacy strategies. The work combines analytical thinking with responsibility and often involves reading carefully, interpreting evidence, preparing documents, applying rules, managing risk, and communicating clearly with stakeholders.`,

  "Investigations & Financial Crime": `Investigations & Financial Crime focuses on identifying misconduct, fraud, money laundering, regulatory breaches, or suspicious activity. People in this pathway analyse evidence, review transactions, prepare reports, interview stakeholders, and support enforcement or risk-control decisions. The work combines analytical thinking with responsibility and often involves reading carefully, interpreting evidence, preparing documents, applying rules, managing risk, and communicating clearly with stakeholders.`,

  "Policy & Public Sector Analysis": `Policy & Public Sector Analysis focuses on researching social, economic, organisational, or public problems and developing evidence-based recommendations. People in this pathway analyse data, consult stakeholders, write briefings, and support decisions in government or public-interest settings. The work combines analytical thinking with responsibility and often involves reading carefully, interpreting evidence, preparing documents, applying rules, managing risk, and communicating clearly with stakeholders.`,

  "Generalist Business Programmes": `Generalist Business Programmes provide broad exposure to different areas of an organisation, including operations, strategy, finance, marketing, HR, projects, and commercial teams. Professionals in this pathway rotate across functions, learn how organisations work from multiple angles, and build the foundations for future management or leadership roles. The work combines commercial awareness with organisation and often involves analysis, planning, stakeholder communication, process improvement, project coordination, performance tracking, or change delivery.`,

  "Operations & Supply Chain": `Operations & Supply Chain focuses on how goods, services, information, and resources move through organisations. Professionals in this pathway analyse workflows, coordinate suppliers, improve processes, manage capacity, reduce waste, and help ensure that products or services are delivered efficiently, reliably, and at scale. The work combines commercial awareness with organisation and often involves analysis, planning, stakeholder communication, process improvement, project coordination, performance tracking, or change delivery.`,

  "Business Analysis": `Business Analysis focuses on understanding organisational problems, user needs, processes, data, and requirements so that teams can improve systems, services, or ways of working. Professionals in this pathway gather evidence, map workflows, identify gaps, clarify requirements, and translate business needs into practical solutions. The work combines commercial awareness with organisation and often involves analysis, planning, stakeholder communication, process improvement, project coordination, performance tracking, or change delivery.`,

  "Project, PMO & Transformation": `Project, PMO & Transformation focuses on planning, coordinating, and delivering organisational change. Professionals in this pathway help manage timelines, governance, risks, budgets, reporting, dependencies, and stakeholder communication so that complex initiatives move from ideas into practical implementation. The work combines commercial awareness with organisation and often involves analysis, planning, stakeholder communication, process improvement, project coordination, performance tracking, or change delivery.`,

  "Consulting & Strategic Improvement": `Consulting & Strategic Improvement focuses on helping organisations diagnose problems, identify opportunities, improve performance, and make better strategic decisions. Professionals in this pathway analyse evidence, structure problems, develop recommendations, and support change across areas such as growth, operations, technology, people, and organisational strategy. The work combines commercial awareness with organisation and often involves analysis, planning, stakeholder communication, process improvement, project coordination, performance tracking, or change delivery.`,

  "Business Development & Commercial Partnerships": `Business Development & Strategic Partnerships focuses on creating growth through new relationships, markets, collaborations, and commercial opportunities. Professionals in this pathway identify prospects, build partnerships, negotiate opportunities, understand customer or partner needs, and help organisations expand through external relationships. The work combines commercial judgement with relationship-building and often involves prospecting, pitching, partnership development, account growth, market understanding, negotiation, and cross-functional collaboration.`,

  "HR, People & Organisations": `HR, People & Organisations focuses on how organisations attract, develop, support, organise, and retain people. Professionals in this pathway help shape recruitment, employee experience, learning and development, performance, workplace culture, people operations, and organisational change. The work combines commercial awareness with organisation and often involves analysis, planning, stakeholder communication, process improvement, project coordination, performance tracking, or change delivery.`,

  "Investment Banking & Corporate Finance": `Investment Banking & Corporate Finance focuses on major financial decisions such as mergers and acquisitions, capital raising, valuations, restructuring, and strategic transactions. People in this pathway analyse companies, build financial models, prepare deal materials, and support clients through high-stakes corporate decisions. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Equity Research & Investment Research": `Equity Research & Investment Research focuses on analysing companies, sectors, markets, and investment opportunities to support financial decisions. People in this pathway build valuation models, read financial statements, assess strategy and risk, and produce recommendations or investment views. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Asset & Wealth Management": `Asset & Wealth Management focuses on managing investments for individuals, institutions, pension funds, or clients with long-term financial goals. People in this pathway analyse portfolios, assess markets, support investment decisions, manage client information, and help grow or protect wealth. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Commercial & Corporate Banking": `Commercial & Corporate Banking focuses on providing financial services, lending, cash management, and relationship support to businesses and larger organisations. People in this pathway assess credit, analyse company performance, manage client relationships, and structure banking solutions. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Markets & Trading": `Markets & Trading focuses on analysing, buying, selling, and managing financial instruments such as shares, currencies, commodities, bonds, and derivatives across global financial markets. People in this pathway interpret market movements, assess risk, and make rapid decisions based on financial data, economic events, and market behaviour. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Treasury & Liquidity": `Treasury & Liquidity focuses on managing an organisation’s cash, funding, liquidity, financial risk, and access to capital. People in this pathway monitor cash flows, manage funding needs, support hedging decisions, and help ensure organisations can meet obligations and operate securely. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Risk, Compliance & Controls": `Risk, Compliance & Controls focuses on identifying, measuring, monitoring, and managing financial, operational, regulatory, or conduct risks. People in this pathway test controls, review processes, analyse exposure, support audits, and help organisations operate safely and responsibly. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Banking Operations & Middle Office": `Banking Operations & Middle Office focuses on the processes, controls, data, and trade support that keep financial services running accurately behind the scenes. People in this pathway reconcile transactions, monitor controls, support trade lifecycle processes, and manage operational risk. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Accounting, Audit & Assurance": `Accounting, Audit & Assurance focuses on financial records, reporting, controls, and independent review of organisational information. People in this pathway prepare accounts, test evidence, review financial statements, assess controls, and help stakeholders trust financial information. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Sustainable Finance & Impact Investing": `Sustainable Finance & Impact Investing focuses on directing capital towards organisations, projects, and investments that consider environmental, social, governance, or impact outcomes alongside financial performance. People in this pathway analyse ESG data, assess impact, evaluate risks, and support responsible investment decisions. The work combines numerical confidence with commercial judgement and often involves financial analysis, modelling, reporting, client work, market awareness, risk assessment, and careful decision support.`,

  "Venture Building & Founder": `Venture Building & Founder focuses on creating, testing, and growing new businesses, products, services, or platforms from early-stage ideas. Professionals in this pathway identify unmet needs, validate opportunities, develop business models, build teams, secure resources, and adapt quickly in uncertain and fast-changing environments. The work combines creativity with commercial action and often involves experimentation, customer discovery, pitching, partnerships, operations, growth, product development, and rapid problem-solving.`,

  "Start-up Operations": `Start-up Operations focuses on making early-stage ventures work day to day and scale effectively. Professionals in this pathway build processes, coordinate teams, solve practical problems, support customers, manage internal systems, and help founders turn fast-moving ideas into organised execution. The work combines creativity with commercial action and often involves experimentation, customer discovery, pitching, partnerships, operations, growth, product development, and rapid problem-solving.`,

  "Product Growth & Business Development in Start-ups": `Product Growth & Business Development in Start-ups focuses on improving what a venture offers, how quickly it reaches users or customers, and how it finds early commercial traction. Professionals in this pathway test ideas, analyse user behaviour, run experiments, improve product journeys, support acquisition, and use feedback to help ventures grow. The work combines creativity with commercial action and often involves experimentation, customer discovery, pitching, partnerships, operations, growth, product development, and rapid problem-solving.`,

  "Venture Capital, Accelerators & Innovation Support": `Venture Capital, Accelerators & Innovation Support focuses on helping start-ups develop, secure investment, and grow. Professionals in this pathway assess ventures, analyse markets, support founders, run programmes, prepare investment materials, and connect new businesses with funding, expertise, and networks. The work combines creativity with commercial action and often involves experimentation, customer discovery, pitching, partnerships, operations, growth, product development, and rapid problem-solving.`,

  "Brand & Marketing Strategy": `Brand & Marketing Strategy focuses on defining how an organisation, product, or service should be positioned, understood, and remembered by its audience. People in this pathway analyse customers, competitors, trends, and messaging to shape campaigns, brand direction, and market plans. The work combines creativity with audience understanding and often involves research, messaging, campaign planning, content, analytics, storytelling, reputation, and communication across digital or traditional channels.`,

  "Performance Marketing & Growth": `Performance Marketing & Growth focuses on measurable marketing activity designed to attract, convert, and retain customers. People in this pathway run digital campaigns, analyse conversion data, test channels, optimise paid media, email, CRM, or growth funnels. The work combines creativity with audience understanding and often involves research, messaging, campaign planning, content, analytics, storytelling, reputation, and communication across digital or traditional channels.`,

  "PR & Communications": `PR & Communications focuses on reputation, messaging, media relationships, stakeholder engagement, and public understanding. People in this pathway write content, prepare statements, manage campaigns, handle press activity, and help organisations communicate clearly in moments that matter. The work combines creativity with audience understanding and often involves research, messaging, campaign planning, content, analytics, storytelling, reputation, and communication across digital or traditional channels.`,

  "Market Research & Audience Insight": `Market Research & Audience Insight focuses on understanding audiences, markets, competitors, and behaviour through evidence. People in this pathway design research, analyse survey or interview data, interpret trends, and help organisations make better communication, product, and brand decisions. The work combines creativity with audience understanding and often involves research, messaging, campaign planning, content, analytics, storytelling, reputation, and communication across digital or traditional channels.`,

  "Content & Social Media": `Content & Social Media focuses on creating, publishing, and managing messages across digital channels to engage audiences. People in this pathway develop posts, videos, campaigns, editorial plans, community content, and performance insights that shape how brands show up online. The work combines creativity with audience understanding and often involves research, messaging, campaign planning, content, analytics, storytelling, reputation, and communication across digital or traditional channels.`,

  "Product & Industrial Design": `Product & Industrial Design focuses on designing physical products, objects, tools, equipment, or consumer goods that are useful, usable, manufacturable, and visually coherent. People in this pathway research users, sketch concepts, prototype ideas, test materials, and refine designs for production. The work combines imagination with practical delivery and often involves research, sketching, prototyping, visual judgment, digital tools, storytelling, user feedback, and attention to how people experience ideas.`,

  "Graphic Design & Visual Communication": `Graphic Design & Visual Communication focuses on turning ideas, information, and messages into clear visual form. People in this pathway design layouts, identities, campaigns, illustrations, digital assets, packaging, or brand materials that communicate meaning quickly and memorably. The work combines imagination with practical delivery and often involves research, sketching, prototyping, visual judgment, digital tools, storytelling, user feedback, and attention to how people experience ideas.`,

  "Animation & Motion Design": `Animation & Motion Design focuses on creating movement, visual storytelling, and dynamic digital content for film, games, advertising, education, interfaces, and social media. People in this pathway develop storyboards, animate characters or graphics, edit sequences, and bring ideas to life through motion. The work combines imagination with practical delivery and often involves research, sketching, prototyping, visual judgment, digital tools, storytelling, user feedback, and attention to how people experience ideas.`,

  "Digital Design & Multimedia": `Digital Design & Multimedia focuses on creating visual and interactive content across websites, apps, campaigns, screens, and digital platforms. People in this pathway combine design, media production, user awareness, and digital tools to build engaging online experiences. The work combines imagination with practical delivery and often involves research, sketching, prototyping, visual judgment, digital tools, storytelling, user feedback, and attention to how people experience ideas.`,

  "Environmental Science & Monitoring": `Environmental Science & Monitoring focuses on measuring, assessing, and interpreting environmental conditions such as air, water, land, biodiversity, pollution, and ecosystems. People in this pathway collect data, conduct fieldwork, prepare reports, and support evidence-based environmental decisions. The work combines purpose with evidence and often involves environmental data, policy, reporting, stakeholder engagement, risk assessment, systems thinking, and practical sustainability planning.`,

  "Sustainability & ESG Advisory": `Sustainability & ESG Advisory focuses on helping organisations understand, measure, report, and improve their environmental, social, and governance performance. People in this pathway analyse data, advise on targets, prepare disclosures, support strategy, and help organisations meet stakeholder and regulatory expectations. The work combines purpose with evidence and often involves environmental data, policy, reporting, stakeholder engagement, risk assessment, systems thinking, and practical sustainability planning.`,

  "Circular Economy & Sustainable Supply Chains": `Circular Economy & Sustainable Supply Chains focuses on reducing waste, improving resource use, and making products, materials, and supply networks more sustainable. People in this pathway analyse supply chains, redesign processes, assess suppliers, and support circular or low-impact business models. The work combines purpose with evidence and often involves environmental data, policy, reporting, stakeholder engagement, risk assessment, systems thinking, and practical sustainability planning.`,

  "Environmental Policy & Impact Assessment": `Environmental Policy & Impact Assessment focuses on understanding how projects, policies, or developments affect the environment and communities. People in this pathway assess risks, prepare impact reports, interpret regulation, consult stakeholders, and support better planning decisions. The work combines purpose with evidence and often involves environmental data, policy, reporting, stakeholder engagement, risk assessment, systems thinking, and practical sustainability planning.`,

  "Net Zero, Climate & Sustainability Strategy": `Net Zero, Climate & Sustainability Strategy focuses on helping organisations reduce emissions, manage climate risks, and plan long-term sustainability transitions. People in this pathway analyse carbon data, develop roadmaps, advise on targets, and support strategic change. The work combines purpose with evidence and often involves environmental data, policy, reporting, stakeholder engagement, risk assessment, systems thinking, and practical sustainability planning.`,

  "International Relations, Policy & Geopolitical Analysis": `International Relations, Policy & Geopolitical Analysis focuses on understanding global politics, institutions, conflict, trade, security, and international decision-making. People in this pathway analyse events, produce briefings, assess risks, and support policy or organisational responses to global change. The work combines contextual understanding with communication and often involves research, writing, language, policy, cultural interpretation, stakeholder work, and careful analysis of social or international issues.`,

  "Languages, Translation & Localisation": `Languages, Translation & Localisation focuses on helping messages, products, services, and content work across languages and cultures. People in this pathway translate, adapt, edit, interpret, and localise communication so that it is accurate, culturally appropriate, and accessible. The work combines contextual understanding with communication and often involves research, writing, language, policy, cultural interpretation, stakeholder work, and careful analysis of social or international issues.`,

  "International Development & NGO Programmes": `International Development & NGO Programmes focuses on improving social, economic, health, education, or humanitarian outcomes across communities and countries. People in this pathway coordinate programmes, monitor impact, manage partners, support funding, and work on practical responses to global challenges. The work combines contextual understanding with communication and often involves research, writing, language, policy, cultural interpretation, stakeholder work, and careful analysis of social or international issues.`,

  "Social Research & Cultural Analysis": `Social Research & Cultural Analysis focuses on understanding societies, communities, identities, behaviour, and cultural change through research. People in this pathway collect and analyse qualitative or quantitative evidence, interpret social patterns, and communicate insights for policy, services, media, or organisations. The work combines contextual understanding with communication and often involves research, writing, language, policy, cultural interpretation, stakeholder work, and careful analysis of social or international issues.`,

  "Intelligence, Public Service & Security Analysis": `Intelligence, Public Service & Security Analysis focuses on interpreting information that supports public safety, national interests, policy, or operational decisions. People in this pathway analyse evidence, assess risks, produce briefings, and help decision-makers understand complex threats or situations. The work combines contextual understanding with communication and often involves research, writing, language, policy, cultural interpretation, stakeholder work, and careful analysis of social or international issues.`,

};

module.exports = { PATHWAY_DESCRIPTIONS };